from test_ingredients import IngredientViewTests
from test_liquors import LiquorViewTests
from test_order_beverages import OrderBeverageViewTests
from test_user_view import UserViewTests
from test_beverages import BeverageViewTests
from test_orders import OrderTests