# Generated by Django 4.1.3 on 2024-08-20 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dranksforyouapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbeverage',
            old_name='beverage',
            new_name='beverage_id',
        ),
        migrations.RenameField(
            model_name='orderbeverage',
            old_name='order',
            new_name='order_id',
        ),
    ]
