# Generated by Django 4.1.3 on 2024-09-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dranksforyouapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.CharField(default='default_image_url.jpg', max_length=100),
        ),
    ]
