# Generated by Django 4.1.3 on 2024-08-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dranksforyouapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beverage_name', models.CharField(max_length=55)),
                ('liquor_id', models.CharField(max_length=50)),
                ('ingredient', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
    ]
